POST http://localhost:3000/case/create
Content-Type: application/json

{
    "uuidAssignedUser": "adfjkghad",
    "uuidOwnerUser" : "adfjkghad",
    "uuidPersonPatient": "adfjkghad",
    "uuidStage": "stage1",
    "reasonForConsultation": "ansiedad"
}